### ISSUE TITLE
fatal: early EOF OSX

### ISSUE THREAD

**Issue by oliverwalton** [houseabsolute/catalauncher#2]
OSX VERSION: 10.15.7

Ive been trying to install catalauncher on my Mac as this seems like the only launcher that might be capable of running on Mac. when I run it I get this docker failure

> Using config file: /Users/oliverwalton/.catalauncher/config.toml
> Getting list of builds from http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/Tiles/
> Found 20 builds
> You have the latest build, #11581, released 2021-04-15 20:59
> Updating extras git repo
> Copying MSX++UnDeadPeopleEdition tileset to game dir
> Copying RRFSounds soundpack to game dir
> Pulling the latest houseabsolute/cataplayer-launcher image
> Could not run "docker run --rm --user 501:20 -v /etc/machine-id:/etc/machine-id -v /run/user/501/pulse:/run/user/501/pulse -v /var/lib/dbus:/var/lib/dbus -v /Users/oliverwalton/.pulse:/.pulse -e DISPLAY -device /dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix -v /Users/oliverwalton/.catalauncher/game-data:/data /Users/oliverwalton/.catalauncher/builds/11581/cataclysmdda-0.E:/game -w /game houseabsolute/catalauncher-player:latest ./cataclysm-tiles --savedir /data/save/ --configdir /data/config/ --memorialdir /data/graveyard/": exit status 127
> 
> docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

**Comment by autarch** [comment]
I'm going to close this and comment on it in #1, which already details some other macOS issues.

**Comment by oliverwalton** [comment]
Fine by me. Thought I'd just highlight it
